jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager || true

  zap_baseline:
    machine: true
    steps:
      - checkout

      - run: |
          docker pull hysnsec/zap:2.16.1
          docker run --user root --rm -v $(pwd):/zap/wrk:rw -w /zap hysnsec/zap:2.16.1 zap-baseline.py -t https://prod-ixqn1ykn.stg.lab.practical-devsecops.training -J zap-output.json || true

      - store_artifacts:
          path: zap-output.json
          destination: zap-artifact

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          when: on_fail         # Even if the job fails, continue to the next stages

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build
      - zap_baseline:
          requires:
            - test
      - integration:
          requires:
            - oast-snyk
      - prod:
          type: approval
          requires:
            - integration
